# Generated by Django 4.1.5 on 2023-02-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
